# Generated by Django 6.0.7 on 2026-07-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='profile_image',
            field=models.ImageField(blank=True, default='vendors/profile/default.png', null=True, upload_to='vendors/profile/'),
        ),
    ]
