# Generated by Django 6.0.7 on 2026-07-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
