# Generated by Django 6.0.7 on 2026-07-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
